[
  { name: 'Satay', price: 11.90, category: 'starters' },
  { name: 'Curry Puff', price: 9.00, category: 'starters' },
  { name: 'Rojak Mamak', price: 12.90, category: 'starters' },
  { name: 'Deep Fried Calamari', price: 12.90, category: 'starters' },
  { name: 'Spring Rolls', price: 7.50, category: 'starters' },
  { name: 'Tamarind Tiger Prawn', price: 16.90, category: 'starters' },
  { name: 'Chicken Salad', price: 10.90, category: 'starters' },
  { name: 'Tom Yum Ayam', price: 12.90, category: 'starters' },
  { name: 'Mixed Platter', price: 30.00, category: 'starters' },
  { name: 'Chicken Curry Corner', price: 18.90, category: 'CurryCorner' },
  { name: 'Lamb Curry Corner', price: 18.90, category: 'CurryCorner' },
  { name: 'Fish & Okra Gulai', price: 21.90, category: 'Gulai' },
  { name: 'Prawn Gulai', price: 21.90, category: 'Gulai' },
  { name: 'Chicken Sambal', price: 18.90, category: 'Sambal' },
  { name: 'Fish Sambal', price: 21.90, category: 'Sambal' },
  { name: 'Prawn Sambal', price: 21.90, category: 'Sambal' },
  { name: 'Squid Sambal', price: 21.90, category: 'Sambal' },
  { name: 'Beef Rendang', price: 18.90, category: 'Rendang' },
  { name: 'Lamb Rendang', price: 18.90, category: 'Rendang' },
  { name: 'Chicken Rendang', price: 18.90, category: 'Rendang' },
  { name: 'Chicken Masak Lemak', price: 18.90, category: 'MasakLemak' },
  { name: 'Fish Masak Lemak', price: 21.90, category: 'MasakLemak' },
  { name: 'Vege Masak Lemak', price: 15.90, category: 'MasakLemak' },
  { name: 'Chicken Nasi Lemak', price: 19.90, category: 'NasiLemak' },
  { name: 'Beef Nasi Lemak', price: 19.90, category: 'NasiLemak' },
  { name: 'Chicken Kurma', price: 18.90, category: 'Kurma' },
  { name: 'Lamb Kurma', price: 18.90, category: 'Kurma' },
  { name: 'Vege Dhal Curry', price: 15.90, category: 'Garden' },
  { name: 'Gado Gado', price: 15.90, category: 'Garden' },
  { name: 'Chicken Stir Fry', price: 18.90, category: 'Chinese' },
  { name: 'Beef Stir Fry', price: 18.90, category: 'Chinese' },
  { name: 'Prawn Stir Fry', price: 21.90, category: 'Chinese' },
  { name: 'Calamari Stir Fry', price: 21.90, category: 'Chinese' },
  { name: 'Vege Stir Fry', price: 15.90, category: 'Chinese' },
  { name: 'Fish Perathal', price: 21.90, category: 'Special' },
  { name: 'Chicken Perathal', price: 18.90, category: 'Special' },
  { name: 'Lamb Perathal', price: 18.90, category: 'Special' },
  { name: 'Butter Chicken', price: 18.90, category: 'Special' },
  { name: 'Chicken Dosa', price: 17.90, category: 'Dosa' },
  { name: 'Lamb Dosa', price: 17.90, category: 'Dosa' },
  { name: 'Masala Dosa', price: 15.90, category: 'Dosa' },
  { name: 'Plain Dosa', price: 8.00, category: 'Dosa' },
  { name: 'Mee Goreng Mamak', price: 17.90, category: 'Hawkers' },
  { name: 'Curry Laksa', price: 17.90, category: 'Hawkers' },
  { name: 'Mee Goreng', price: 17.90, category: 'Hawkers' },
  { name: 'Nasi Goreng', price: 17.90, category: 'Hawkers' },
  { name: 'Chicken Murtabak', price: 18.90, category: 'Roti' },
  { name: 'Kothu Roti', price: 18.90, category: 'Roti' },
  { name: 'Plain Roti', price: 3.00, category: 'Roti' },
  { name: 'Garlic Roti', price: 3.50, category: 'Roti' },
  { name: 'Egg & Onion Roti', price: 4.50, category: 'Roti' },
  { name: 'Coconut Rice', price: 2.50, category: 'Side' },
  { name: 'Pappadoms', price: 1.50, category: 'Side' },
  { name: 'Peanut Sauce', price: 3.00, category: 'Side' },
  { name: 'Raita', price: 4.90, category: 'Side' },
  { name: 'Extra', price: 0.50, category: 'Side' },
  { name: 'Extra02', price: 1.00, category: 'Side' },
  { name: 'Extra03', price: 2.00, category: 'Side' },
  { name: 'Extra04', price: -1.00, category: 'Side' },
  { name: 'BYO', price: 5.00, category: 'whitewine' },
  { name: 'Chardonnay Glass', price: 7.50, category: 'whitewine' },
  { name: 'Chardonnay Bottle', price: 34.00, category: 'whitewine' },
  { name: 'Gewurztraminer Glass', price: 7.50, category: 'whitewine' },
  { name: 'Gewurztraminer Bottle', price: 34.00, category: 'whitewine' },
  { name: 'Pinot Gris Glass', price: 7.50, category: 'whitewine' },
  { name: 'Pinot Gris Bottle', price: 34.00, category: 'whitewine' },
  { name: 'Riesling Glass', price: 8.50, category: 'whitewine' },
  { name: 'Riesling Bottle', price: 37.00, category: 'whitewine' },
  { name: 'Sauvingnon Glass', price: 7.50, category: 'whitewine' },
  { name: 'Sauvingnon Glass', price: 34.00, category: 'whitewine' },
  { name: 'Sparklink Bottle', price: 34.00, category: 'whitewine' },
  { name: 'Merlot Glass', price: 7.50, category: 'Red' },
  { name: 'Merlot Bottle', price: 34.00, category: 'Red' },
  { name: 'Cabernet Glass', price: 7.50, category: 'Red' },
  { name: 'Cabernet Bottle', price: 34.00, category: 'Red' },
  { name: 'Shiraz Glass', price: 7.50, category: 'Red' },
  { name: 'Shiraz Bottle', price: 34.00, category: 'Red' },
  { name: 'Pinot Noir Glass', price: 7.50, category: 'Red' },
  { name: 'Pinot Noir Bottle', price: 34.00, category: 'Red' },
  { name: 'Syrah Glass', price: 7.50, category: 'Red' },
  { name: 'Syrah Bottle', price: 34.00, category: 'Red' },
  { name: 'Rose Glass', price: 7.50, category: 'Red' },
  { name: 'Rose Bottle', price: 34.00, category: 'Red' },
  { name: 'Asahi', price: 8.00, category: 'Beer' },
  { name: 'Corona', price: 8.00, category: 'Beer' },
  { name: 'Heineken', price: 7.00, category: 'Beer' },
  { name: 'Heineken Light', price: 7.50, category: 'Beer' },
  { name: 'Kingfisher Lager', price: 7.50, category: 'Beer' },
  { name: 'Monteiths Range', price: 7.00, category: 'Beer' },
  { name: 'Steinlager', price: 8.00, category: 'Beer' },
  { name: 'Stella Artois', price: 8.00, category: 'Beer' },
  { name: 'Tiger Lager ', price: 8.00, category: 'Beer' },
  { name: 'Tuatara Pilsner ', price: 8.00, category: 'Beer' },
  { name: 'Coke', price: 3.50, category: 'SoftDrinks' },
  { name: 'Diet Coke', price: 3.50, category: 'SoftDrinks' },
  { name: 'Sprite', price: 3.50, category: 'SoftDrinks' },
  { name: 'L&P', price: 3.50, category: 'SoftDrinks' },
  { name: 'Mango Lassi', price: 4.50, category: 'SoftDrinks' },
  { name: 'Sweet Lassi', price: 4.00, category: 'SoftDrinks' },
  { name: 'Apple Juice', price: 4.00, category: 'SoftDrinks' },
  { name: 'Apple Cider', price: 7.00, category: 'SoftDrinks' },
  { name: 'Pinapple Juice', price: 4.00, category: 'SoftDrinks' },
  { name: 'Orange Juice', price: 4.00, category: 'SoftDrinks' },
  { name: 'Ginger Beer', price: 4.00, category: 'SoftDrinks' },
  { name: 'Soda Water', price: 3.50, category: 'SoftDrinks' },
  { name: 'Sparkling Water', price: 3.50, category: 'SoftDrinks' },
  { name: 'Tonic Water', price: 3.50, category: 'SoftDrinks' },
  { name: 'Gin', price: 4.50, category: 'Sprites' },
  { name: 'Tequila', price: 4.50, category: 'Sprites' },
  { name: 'Bourboun', price: 4.50, category: 'Sprites' },
  { name: 'Vodka', price: 4.50, category: 'Sprites' },
  { name: 'Whisky', price: 4.50, category: 'Sprites' },
  { name: 'White Rum', price: 4.50, category: 'Sprites' },
  { name: 'Malaysian Teh Tarik', price: 4.00, category: 'HotDrinks' },
  { name: 'Malaysian Kopi', price: 4.00, category: 'HotDrinks' },
  { name: 'Ginger Masala Tea', price: 4.00, category: 'HotDrinks' },
  { name: 'Green Tea', price: 4.00, category: 'HotDrinks' },
  { name: 'Black Tea', price: 4.00, category: 'HotDrinks' },

]
